"""Add message chunking support for streaming

Revision ID: 1f536042ef66
Revises: f77f81584ee0
Create Date: 2025-11-02 22:30:48.516169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f536042ef66'
down_revision = 'f77f81584ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('chunk_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_chunks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('total_chunks')
        batch_op.drop_column('chunk_index')
        batch_op.drop_column('message_group_id')

    # ### end Alembic commands ###
