"""add_conversation_memory_fields

Revision ID: f77f81584ee0
Revises: 9162c1d83933
Create Date: 2025-10-11 20:16:28.655830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77f81584ee0'
down_revision = '9162c1d83933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pruned_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_summary_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('last_summary_at')
        batch_op.drop_column('pruned_count')
        batch_op.drop_column('memory_summary')

    # ### end Alembic commands ###
